### ISSUE TITLE
Alexa Launch: _processIntent Not Defined

### ISSUE THREAD

**Issue by chadevanssf** [salesforce/violet-conversations#3]
There is a bug when launching from an Alexa device.

ReferenceError: _processIntent is not defined
2018-02-16T15:21:54.848332+00:00 app[web.1]:     at alexa.app.launchFunc (/app/node_modules/violet/lib/violet.js:101:5)
2018-02-16T15:21:54.848334+00:00 app[web.1]:     at /app/node_modules/alexa-app/index.js:575:41
2018-02-16T15:21:54.848336+00:00 app[web.1]:     at tryCatcher (/app/node_modules/alexa-app/node_modules/bluebird/js/main/util.js:26:23)
2018-02-16T15:21:54.848354+00:00 app[web.1]:     at Promise._settlePromiseFromHandler (/app/node_modules/alexa-app/node_modules/bluebird/js/main/promise.js:510:31)
2018-02-16T15:21:54.848357+00:00 app[web.1]:     at Promise._settlePromiseAt (/app/node_modules/alexa-app/node_modules/bluebird/js/main/promise.js:584:18)
2018-02-16T15:21:54.848359+00:00 app[web.1]:     at Promise._settlePromises (/app/node_modules/alexa-app/node_modules/bluebird/js/main/promise.js:700:14)
2018-02-16T15:21:54.848360+00:00 app[web.1]:     at Async._drainQueue (/app/node_modules/alexa-app/node_modules/bluebird/js/main/async.js:123:16)
2018-02-16T15:21:54.848362+00:00 app[web.1]:     at Async._drainQueues (/app/node_modules/alexa-app/node_modules/bluebird/js/main/async.js:133:10)
2018-02-16T15:21:54.848363+00:00 app[web.1]:     at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/alexa-app/node_modules/bluebird/js/main/async.js:15:14)
2018-02-16T15:21:54.848365+00:00 app[web.1]:     at runCallback (timers.js:756:18)
2018-02-16T15:21:54.848367+00:00 app[web.1]:     at tryOnImmediate (timers.js:717:5)
2018-02-16T15:21:54.848368+00:00 app[web.1]:     at processImmediate [as _immediateCallback] (timers.js:697:5)

**Comment by vineet-sinha** [comment]
@chadevanssf - thanks for the bug report. I see why it is happening and will get a fix out.

In the meantime - you should be able to still use the skill without using the `launch` command.

**Comment by chadevanssf** [comment]
It was a small fix, added to my fork here:

https://github.com/chadevanssf/violet-conversations/commit/5b85c9289752e1e6a2612f59feeeb1fa48998fd1

**Comment by vineet-sinha** [comment]
Awesome. Do you want to submit a PR here?
